### ISSUE TITLE
[BUG] Speakers volume always reset to max (100%) after reboot

### ISSUE THREAD

**Issue by sezaru** [nix-community/nixos-apple-silicon#352]
I noticed that every time I reboot my machine (I think it happens if I just logout and login again), my speakers volume will reset to 100%.

After troubleshooting a little bit, I found that the issue seems to be related to the config file that is added to `/etc/pipewire/pipewire.conf.d` `99-asahi.conf`.

Just running `./asahi-diagnose` will complain about that file.

So, what I did to fix it for me was to do the following changes:

First, I will add the setup sound option as per usual:

```nix
hardware.asahi.setupAsahiSound = true;
```

That, by default, will add the above file and trigger the issue, so now I will force it to not do that:

```nix
services.pipewire.configPackages = lib.mkForce [];
services.pipewire.wireplumber.configPackages = lib.mkForce [];

environment.systemPackages = [pkgs.asahi-audio];
```

The first two lines remove `pkgs.asahi-audio` from the `configPackages` for `pipewire` and `wireplumber`, doing that means that the `99-asahi.conf` file will not be copied to `/etc/pipewire/pipewire.conf.d`.

This also means that now there is not link to `pkgs.asahi-audio`, so we manually add it to our `systemPackages`.

After doing that, now the audio will correctly retain its volume after reboots without an issue.

Also, after that change, `asahi-diagnose` will stop complaining that the audio configuration is broken.

So, is there a reason that we are adding that config file? AFAIK that was necessary when they started working on the sound support, but now is not needed anymore and they also recommend that people remove that file manually (with Fedora/Arch Asahi) if they have it to avoid having sound issues.

**Comment by ghost** [comment]
See https://github.com/nix-community/nixos-apple-silicon/pull/357 

This change works, though placing `pkgs.asahi-audio` in `environment.systemPackages` isn't required since the lv2 plugins are only passed into pipewire if they are in the `configPackages` attribute's list. I've proposed changing the sound module to just add the lv2 plugins among other changes.

**Comment by sezaru** [comment]
I want to test that out, but just to make sure I understood it correctly, using that I still can have `services.pipewire.enable = true;` on my end to use pipewire correct?

Edit:

So, I just tried it by copying the changes to my module, basically I have this in my file:

```nix
{
  config,
  lib,
  pkgs,
  ...
}: {
  # From Asahi audio module:

  # can't be used by Asahi sound infrastructure
  services.pulseaudio.enable = lib.mkForce false;
  # enable pipewire to run real-time and avoid audible glitches
  security.rtkit.enable = true;
  # set up pipewire with the supported capabilities (instead of pulseaudio)
  # and asahi-audio configs and plugins

  services.pipewire.extraLv2Packages = with pkgs; [
    lsp-plugins
    bankstown-lv2
    triforce-lv2
  ];

  # set up enivronment so that UCM configs are used as well
  environment.variables.ALSA_CONFIG_UCM2 = "${pkgs.alsa-ucm-conf-asahi}/share/alsa/ucm2";
  systemd.user.services.pipewire.environment.ALSA_CONFIG_UCM2 =
    config.environment.variables.ALSA_CONFIG_UCM2;
  systemd.user.services.wireplumber.environment.ALSA_CONFIG_UCM2 =
    config.environment.variables.ALSA_CONFIG_UCM2;

  # enable speakersafetyd to protect speakers
  systemd.packages = [ pkgs.speakersafetyd ];
  services.udev.packages = [ pkgs.speakersafetyd ];

  # My custom settings:

  services.pipewire = {
    enable = true;

    alsa.enable = true;
    alsa.support32Bit = true;

    pulse.enable = true;

    wireplumber.enable = true;
  };
}
```

After doing that, sound was back to 100% every time I login.

**Comment by ghost** [comment]
Let's try swapping your current n-a-s flake input with my PR branch `"github:normalcea/nixos-apple-silicon/sound-module-rework"`

And just enable in your configuration:

```nix
hardware.asahi = {
    enable = true;
    setupAsahiSound = true;
}
```

and

```nix
 services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
 };
```
I'm using the GNOME nixos module, so pipewire is implicitly activated in my case and I don't have to set it manually. Perhaps this may be a difference to how the GNOME and Niri modules are set up?

**Comment by sezaru** [comment]
Indeed, doing that way worked great 👍 

Looking forward for the PR to be merged

**Comment by ghost** [comment]
Knowing that this works for you means that it would be even better to just deprecate `setupAsahiSound` entirely and add audio components on the condition of pipewire being enabled similar to how we've deprecated the mesa module.

**Comment by dramforever** [comment]
This was the upstream issue mentioned on Fedora Asahi Matrix channel https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4900

**Comment by dramforever** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4900 is fixed in 1.4.10+. Nixpkgs will probably ship 1.6 when it releases. See maybe

- https://github.com/NixOS/nixpkgs/pull/468269

**Comment by B0bby31** [comment]
I am running unstable nixpkgs and can as of now confirm that I have pipewire version 1.6.2, but this issue is still not resolved.

**Comment by dramforever** [comment]
I can sort of confirm this, but the symptom was different. Before, the volume was reset to 100%. Now, the volume slider is reset to the saved value, but the actual volume was still 100% until I actually adjust the volume.

**Comment by B0bby31** [comment]
> I can sort of confirm this, but the symptom was different. Before, the volume was reset to 100%. Now, the volume slider is reset to the saved value, but the actual volume was still 100% until I actually adjust the volume.

Now that you mention it. This is precisely the issue I have, so it is slightly different.

**Comment by eyezahhhh** [comment]
For me, moving volume sliders didn't sync between apps (and weren't actually changing the sink volume) until i played a sound. Then the volume would jump back to 100% and _then_ everything would start working correctly. I had to remove asahi audio config to get it working normally from boot, which also made my laptop remember what the volume should be.

**Comment by reidlabb** [comment]
> I can sort of confirm this, but the symptom was different. Before, the volume was reset to 100%. Now, the volume slider is reset to the saved value, but the actual volume was still 100% until I actually adjust the volume.

i can confirm this is still happening with the newest version of the flake and pipewire 1.6.2 !

i had a similar issue on a t2 mac (it went away after a while, not sure why) and i could "fix" it by turning the volume up and down with keybinds, which put it into the correct state. but weirdly enough on my apple silicon device (16in mbp m1 max), this fix doesn't work until *after* audio starts playing, making this device almost impossible to use in public

**Comment by dramforever** [comment]
This seems to be fixed for me on latest nixos-unstable 1.6.7. This checks out - https://gitlab.freedesktop.org/pipewire/pipewire/-/work_items/5192 is fixed by https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/b09c8d79c5b868dd204b05940483b0203f1400f4 which is in 1.6.6+. I think this can be closed, or closed upon next release.

**Comment by flokli** [comment]
Let's close this now, there's nothing really actionable here anymore.

Planning to do a release once https://nixpk.gs/pr-tracker.html?pr=540766 hits the channels and we bump past it.
